Demo apr 15
kentik/config-snippets-cloud pull request #34
Opened 2021-04-19 11:45 UTC by lukaa12

KNTK-222

2021-04-19 14:41 UTC, mateuszmidor submitted a review, later dismissed
Nice animations!

2021-04-19 15:35 UTC, Fenthick requested changes

2021-04-19 15:35 UTC, Fenthick commented on cloud_AWS/terraform/module/demo/README.md
> +S3 bucket for logs storage. Pleas note that it can take few minutes before AWS start saving logs in bucket.
```suggestion
S3 bucket for logs storage. Please note that it can take few minutes before AWS start saving logs in bucket.
```

2021-04-19 15:35 UTC, Fenthick commented on cloud_AWS/terraform/module/demo/README.md
> +## Now let's check if we have resources in AWS and Kentik Portal created.
```suggestion
## Verify results

Now let's check if we have resources in AWS and Kentik Portal created.
```
shorter header

2021-04-20 09:19 UTC, mateuszmidor approved these changes

2021-04-20 10:09 UTC, Fenthick commented on cloud_AWS/terraform/module/demo/README.md
>  ![](.assets/gifs/checkFlowLogs.gif)
Please rename the PR as well

2021-04-20 10:10 UTC, Fenthick commented on cloud_AWS/terraform/module/demo/README.md
> +S3 bucket for logs storage. Pleas note that it can take few minutes before AWS start saving logs in bucket.
Resolved

2021-04-20 10:10 UTC, Fenthick commented on cloud_AWS/terraform/module/demo/README.md
> +## Now let's check if we have resources in AWS and Kentik Portal created.
Resolved

2021-04-20 10:11 UTC, Fenthick submitted a review, later dismissed

2021-04-21 07:41 UTC, Fenthick submitted a review, later dismissed

2021-04-21 11:10 UTC, mateuszmidor approved these changes

2021-04-21 11:36 UTC, Fenthick approved these changes

2021-04-21 21:28 UTC, mmac-m3a approved these changes

2021-04-21 21:29 UTC, merged