ksynth on ec2 instance
kentik/config-snippets-cloud pull request #61
Opened 2022-06-29 07:17 UTC by jdziurzynski

KNTK-376

Terraform configuration for ksynth agent deployment on AWS ec2 instance.

2022-06-30 09:25 UTC, mateuszmidor commented on synthetics_AWS/terraform/README.md
> +| terraform    | >= 1.0.0 |
better peg the major version to avoid incompatible changes when new major version is released

2022-06-30 09:27 UTC, mateuszmidor commented on synthetics_AWS/terraform/ec2.tf
> +    values = ["ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"]
Note that AMIs get deprecated and unavailable with time, this may deserve at least a comment

2022-06-30 09:29 UTC, mateuszmidor commented on synthetics_AWS/terraform/ec2.tf
> +systemctl start ksynth
ksynth start-stop-start sequence may deserve a comment

2022-06-30 09:29 UTC, mateuszmidor commented on synthetics_AWS/terraform/main.tf
> +  required_version = ">= 1.0"
Please peg major versions

2022-06-30 09:30 UTC, mateuszmidor commented on synthetics_AWS/terraform/main.tf
> +  region  = "us-east-2"
Probably should be a variable

2022-07-12 11:06 UTC, mateuszmidor approved these changes
Looks good

2022-08-03 18:38 UTC, mmac-m3a requested changes
This won't work as-is.

2022-08-03 18:38 UTC, mmac-m3a commented on synthetics_AWS/terraform/ec2.tf
> +echo "KENTIK_COMPANY=${var.plan_id}" >> /etc/default/ksynth
The `plan_id` variable is misnamed. The `KENTIK_COMPANY` variable needs to contain company id, which is a different identifier than `plan_id`. It is also crucial to have an option to provide "kentik environment" parameter (indicating which Kentik instance the agent should join).

2022-08-03 18:38 UTC, mmac-m3a commented on synthetics_AWS/terraform/ec2.tf
> +curl -s https://packagecloud.io/install/repositories/kentik/ksynth/script.deb.sh | sudo bash
Error handling?

2022-08-03 18:38 UTC, mmac-m3a commented on synthetics_AWS/terraform/ec2.tf
> +systemctl start ksynth
This is line is definitely not needed.

2022-08-03 18:38 UTC, mmac-m3a commented on synthetics_AWS/terraform/README.md
> +| plan_id                | Kentik plan ID                                   | string       |         | true     |
`plan_id` is never needed to run `ksynth`. This should be `company_id`.

2022-08-03 18:38 UTC, mmac-m3a commented on synthetics_AWS/terraform/README.md
> +| key_name               | Key name of the Key Pair to use for the instance | string       |         | false    |
What "key pair" are referring to?

2024-12-06 05:45 UTC, jryburn approved these changes
LGTM

2024-12-06 05:45 UTC, merged

2024-12-06 15:12 UTC, jksprattler commented
@jryburn not sure why this was approved but there are several issues with it as-is:
- uses the old rust agent repo in packagecloud which hasn't been in use for 2+ years
- uses unsupported ubuntu focal release from 2020
- poor var naming and explanation of `KENTIK_COMPANY` as `plan_id` this should have been left as `company_id` as previously suggested

2024-12-06 15:27 UTC, jryburn commented
> @jryburn not sure why this was approved but there are several issues with it as-is:
> 
> * uses the old rust agent repo in packagecloud which hasn't been in use for 2+ years
> * uses unsupported ubuntu focal release from 2020
> * poor var naming and explanation of `KENTIK_COMPANY` as `plan_id` this should have been left as `company_id` as previously suggested

Good catch. I'm not sure but I think I approved the wrong PR. I just submitted a new one to revert these changes.